# Generated by Django 3.2.25 on 2024-04-24 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_price_recipe_preco'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recipe',
            new_name='Receita',
        ),
    ]
