# Generated by Django 3.2.25 on 2024-04-25 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20240424_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='categoria',
            new_name='categorias',
        ),
    ]
