# Generated by Django 3.2.25 on 2026-04-08 21:05

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_receita_ingredientes'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.imagem_receita_file_path),
        ),
    ]
