# Generated by Django 3.2.25 on 2026-04-09 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_receita_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='image',
            new_name='imagem',
        ),
    ]
